# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            managers=[
                ('poeple', django.db.models.manager.Manager()),
            ],
        ),
    ]
